package CityStyle_Footwear_System;

import java.sql.*;
import java.util.Vector;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class ApprovalsReturns extends javax.swing.JFrame {
   
   String userRole; // to store user's role who come to this page
    public ApprovalsReturns(String role) {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.userRole = role;
        setupPermissions(); // create permissions
        loadTables();
    }

    ApprovalsReturns() {
      Connect();
      table_discount(); 
    }

  
    
    private void setupPermissions() {  // to control UI by userrole
        if (userRole.equalsIgnoreCase("Cashier")) {
            btnApproveReturn.setVisible(true);
            btnApproveDiscount.setVisible(true);
            panelCashierInput.setVisible(true); // show inputs to cashier (Data input by cashier)
        }
        else {
            btnApproveReturn.setVisible(true);
            btnApproveDiscount.setVisible(true);
            tblReturns.setVisible(true);
            panelCashierInput.setVisible(false); // Manager will not add inputs(REturn/exchange detail) - It is a duty of cashier 
            // Hide discount request inputs from manager(Because of cashier duty)
            jLabel6.setVisible(false);
            jTextFieldBillNo.setVisible(false);
            jLabel7.setVisible(false);
            jTextFieldDiscount.setVisible(false);
            btnRequestDiscount.setVisible(false);
        }
    }
    
    private void loadTables() {
    try {
        Connection con = DatabaseConnection.getConnection();
        
        String sql1 = (userRole.equals("Manager")) ? // load return table 
             "SELECT * FROM public.returns WHERE status='Pending'" :  //Manager will see as pending
             "SELECT * FROM public.returns ORDER BY returnid DESC";
        
        // Load Returns 
        DefaultTableModel model1 = (DefaultTableModel) tblReturns.getModel();
        model1.setRowCount(0);
        ResultSet rs1 = con.createStatement().executeQuery(sql1); 
        while(rs1.next()) {
            model1.addRow(new Object[]{rs1.getInt("returnid"), rs1.getInt("shoeid"), rs1.getInt("qty"), rs1.getString("type"), rs1.getString("reason"), rs1.getString("status")});
        }

        // LOad Discounts 
        DefaultTableModel model2 = (DefaultTableModel) tblDiscounts.getModel();
        model2.setRowCount(0);
        ResultSet rs2 = con.createStatement().executeQuery("SELECT * FROM public.discount_requests WHERE status='Pending'");
        while(rs2.next()) {
            model2.addRow(new Object[]{rs2.getInt("requestid"), rs2.getString("bill_no"), rs2.getBigDecimal("requested_discount"), rs2.getString("status")});
        }
    } catch (Exception e) { JOptionPane.showMessageDialog(this, e.getMessage()); }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDiscounts = new javax.swing.JTable();
        btnApproveDiscount = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        panelCashierInput = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtShoeID = new javax.swing.JTextField();
        txtReason = new javax.swing.JTextField();
        txtQty = new javax.swing.JTextField();
        btnSubmitRequest = new javax.swing.JButton();
        cmbType = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldDiscount = new javax.swing.JTextField();
        jTextFieldBillNo = new javax.swing.JTextField();
        btnRequestDiscount = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReturns = new javax.swing.JTable();
        btnApproveReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText(" Returns /  Exchanges & Discounts");

        tblDiscounts.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblDiscounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Bill No", "Discount %", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblDiscounts);

        btnApproveDiscount.setBackground(new java.awt.Color(51, 51, 255));
        btnApproveDiscount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnApproveDiscount.setText("Approve Discount");
        btnApproveDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveDiscountActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 0, 51));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Shoe Id");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Quantity");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Reason");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Type");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSubmitRequest.setBackground(new java.awt.Color(51, 0, 255));
        btnSubmitRequest.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSubmitRequest.setText("Submit Request");
        btnSubmitRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitRequestActionPerformed(evt);
            }
        });

        cmbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Return", "Exchange" }));
        cmbType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCashierInputLayout = new javax.swing.GroupLayout(panelCashierInput);
        panelCashierInput.setLayout(panelCashierInputLayout);
        panelCashierInputLayout.setHorizontalGroup(
            panelCashierInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCashierInputLayout.createSequentialGroup()
                .addGroup(panelCashierInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelCashierInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtShoeID, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(txtReason))
                .addGap(69, 69, 69)
                .addGroup(panelCashierInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(42, 42, 42)
                .addGroup(panelCashierInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtQty)
                    .addComponent(cmbType, 0, 141, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnSubmitRequest)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCashierInputLayout.setVerticalGroup(
            panelCashierInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCashierInputLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelCashierInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtShoeID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelCashierInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReason)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelCashierInputLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btnSubmitRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Bill No");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Discount %");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnRequestDiscount.setBackground(new java.awt.Color(51, 0, 255));
        btnRequestDiscount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRequestDiscount.setText("Request Discount");
        btnRequestDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestDiscountActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 102));
        jLabel9.setText("Discounts");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 102));
        jLabel8.setText(" Returns / Exchanges ");

        tblReturns.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblReturns.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Shoe ID", "Qty", "Type", "Reason", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblReturns);

        btnApproveReturn.setBackground(new java.awt.Color(51, 51, 255));
        btnApproveReturn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnApproveReturn.setText("Approve ");
        btnApproveReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelCashierInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(btnBack)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(32, 32, 32)
                                                    .addComponent(jTextFieldBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(62, 62, 62)
                                                    .addComponent(jLabel7)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jTextFieldDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btnApproveReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnRequestDiscount))
                                            .addComponent(btnApproveDiscount))))
                                .addGap(0, 18, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelCashierInput, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRequestDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(btnApproveReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnApproveDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveReturnActionPerformed
        int row = tblReturns.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a record first!");
            return;
        }

        // As security perpose,again request manager password before approve
       String inputPass = JOptionPane.showInputDialog(this, "Manager Authorization Required.\nEnter Password:");
    
       if (inputPass == null || inputPass.isEmpty()) return;

       try {
          Connection con = DatabaseConnection.getConnection();
        
        // Check password correctness, comparering with databse
        String checkSql = "SELECT * FROM public.users WHERE password=? AND userrole='Manager'";
        PreparedStatement pstCheck = con.prepareStatement(checkSql);
        pstCheck.setString(1, inputPass);
        ResultSet rs = pstCheck.executeQuery();

        if (rs.next()) {
            // Only if manager password correct
            int retId = (int) tblReturns.getValueAt(row, 0);
            int shoeId = (int) tblReturns.getValueAt(row, 1);
            int qty = (int) tblReturns.getValueAt(row, 2);

            con.setAutoCommit(false); // Do as a Transaction 

            // Approved the status
            PreparedStatement pst1 = con.prepareStatement("UPDATE public.returns SET status='Approved' WHERE returnid=?");
            pst1.setInt(1, retId);
            pst1.executeUpdate();

            // Increase stock because of a return
            PreparedStatement pst2 = con.prepareStatement("UPDATE public.shoe SET qty = qty + ? WHERE shoeid = ?");
            pst2.setInt(1, qty); 
            pst2.setInt(2, shoeId); 
            pst2.executeUpdate();
            con.commit();
            JOptionPane.showMessageDialog(this, "Return Authorized! Stock has been updated.");
            loadTables(); 
        }
        else {
            JOptionPane.showMessageDialog(this, "Invalid Manager Password!", "Authorization Failed", JOptionPane.ERROR_MESSAGE);
        }
    } 
       catch (Exception e)
       {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnApproveReturnActionPerformed

    private void btnApproveDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveDiscountActionPerformed
    int row = tblDiscounts.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a discount request!");
        return;
    }

    // Request manager password
    String inputPass = JOptionPane.showInputDialog(this, "Enter Manager Password to Override Discount:");
    
    if (inputPass == null || inputPass.isEmpty()) return;

    try {
        Connection con = DatabaseConnection.getConnection();
        
        //Check manager details
        String checkSql = "SELECT * FROM public.users WHERE password=? AND userrole='Manager'";
        PreparedStatement pstCheck = con.prepareStatement(checkSql);
        pstCheck.setString(1, inputPass);
        ResultSet rs = pstCheck.executeQuery();

        if (rs.next()) {
            int reqId = Integer.parseInt(tblDiscounts.getValueAt(row, 0).toString());

            // Approve a Discount
            PreparedStatement pst = con.prepareStatement("UPDATE public.discount_requests SET status='Approved' WHERE requestid=?");
            pst.setInt(1, reqId);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Discount Request Approved Successfully!");
            table_discount();
        }
        else {
            JOptionPane.showMessageDialog(this, "Invalid Manager Password!", "Access Denied", JOptionPane.ERROR_MESSAGE);
        }
    } 
    catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnApproveDiscountActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
      if (userRole.equalsIgnoreCase("Manager")) {
            new ManagerDashboard().setVisible(true); // If user is Manager, show Manager dashboard
        } else {
            new CashierDashboard().setVisible(true);//If user is Cashier, show Cashier dashboard
        }
       this.dispose(); // close this page
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTypeActionPerformed

    private void btnSubmitRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitRequestActionPerformed
        // check is inputs are empty
    if (txtShoeID.getText().isEmpty() || txtQty.getText().isEmpty() || txtReason.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill all fields!");
        return;
    }

    try {
        Connection con = DatabaseConnection.getConnection();
        
        // Add data into Returns table
        // save status as 'Pending' 
        String sql = "INSERT INTO public.returns (shoeid, qty, type, reason, status) VALUES (?, ?, ?, ?, 'Pending')";
        
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setInt(1, Integer.parseInt(txtShoeID.getText()));
        pst.setInt(2, Integer.parseInt(txtQty.getText()));
        pst.setString(3, cmbType.getSelectedItem().toString()); // Return or Exchange
        pst.setString(4, txtReason.getText());
        
        pst.executeUpdate();
        
        JOptionPane.showMessageDialog(this, "Return Request Submitted! Waiting for Manager Approval.");
        
        // create Text fields as empty
        txtShoeID.setText("");
        txtQty.setText("");
        txtReason.setText("");
        
        // Refresh the table
        loadTables();
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Shoe ID and Quantity must be numbers!");
    } 
    catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_btnSubmitRequestActionPerformed

    private void table_discount() {
    try {
        Connection con = DatabaseConnection.getConnection();
        // get pending requests from discount_requests table
        PreparedStatement pst = con.prepareStatement("SELECT * FROM public.discount_requests ORDER BY requestid DESC");
        ResultSet rs = pst.executeQuery();
        
        DefaultTableModel dtm = (DefaultTableModel)tblDiscounts.getModel(); 
        dtm.setRowCount(0); //clear table
        
        while (rs.next()) {
            Vector v = new Vector();
            v.add(rs.getString("requestid"));
            v.add(rs.getString("bill_no"));
            v.add(rs.getString("requested_discount"));
            v.add(rs.getString("status"));
            dtm.addRow(v);
        }
    } catch (Exception e) {
    }
}
    
    private void btnRequestDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestDiscountActionPerformed
       
    String billNo = jTextFieldBillNo.getText();
    String discount = jTextFieldDiscount.getText();
    String status = "Pending"; // begining status as pending

    try {
        Connection con = DatabaseConnection.getConnection();
        // Add data into discount_requests table
        PreparedStatement pst = con.prepareStatement("INSERT INTO public.discount_requests (bill_no, requested_discount, status) VALUES (?, ?, ?)");
        pst.setString(1, billNo);
        pst.setDouble(2, Double.parseDouble(discount));
        pst.setString(3, status);
        pst.executeUpdate();

        JOptionPane.showMessageDialog(this, "Discount Request Sent to Manager!");
        
        // Refresh the table
        table_discount(); 
        
        // clear Fields
        jTextFieldBillNo.setText("");
        jTextFieldDiscount.setText("");
        
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_btnRequestDiscountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApprovalsReturns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApprovalsReturns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApprovalsReturns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApprovalsReturns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApprovalsReturns().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApproveDiscount;
    private javax.swing.JButton btnApproveReturn;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequestDiscount;
    private javax.swing.JButton btnSubmitRequest;
    private javax.swing.JComboBox cmbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldBillNo;
    private javax.swing.JTextField jTextFieldDiscount;
    private javax.swing.JPanel panelCashierInput;
    private javax.swing.JTable tblDiscounts;
    private javax.swing.JTable tblReturns;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtReason;
    private javax.swing.JTextField txtShoeID;
    // End of variables declaration//GEN-END:variables

    private void Connect() {
    
    }

  
}
