package CityStyle_Footwear_System;

import java.sql.*; // To connect with sql database(Connection, PreparedStatement, ResultSet)
import javax.swing.JOptionPane; // To show a message box
import javax.swing.table.DefaultTableModel; // Used to manage and manipulate data inside a JTable (e.g., Inventory Report)
import java.util.Vector;  // Used to store and transfer a row of data from the database to the table

public class ManagerDashboard extends javax.swing.JFrame {

    public String userRole = "Manager";
    public ManagerDashboard() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    ManagerDashboard(String userRole) {
        initComponents();  
        this.setResizable(false);
        this.userRole = userRole;
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCheckStock = new javax.swing.JButton();
        btnViewShoes = new javax.swing.JButton();
        btnAddCategory = new javax.swing.JButton();
        btnSearchShoe = new javax.swing.JButton();
        btnCreateCashier = new javax.swing.JButton();
        btnApprovals = new javax.swing.JButton();
        btnPricing = new javax.swing.JButton();
        btnAddShoe = new javax.swing.JButton();
        btnUpdateProfile = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnApprovals1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager Dashboard");
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Manager Dashboard");

        btnCheckStock.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCheckStock.setText("Stock Management");
        btnCheckStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckStockActionPerformed(evt);
            }
        });

        btnViewShoes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnViewShoes.setText("Shoe Management");
        btnViewShoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewShoesActionPerformed(evt);
            }
        });

        btnAddCategory.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddCategory.setText("Category Management");
        btnAddCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCategoryActionPerformed(evt);
            }
        });

        btnSearchShoe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearchShoe.setText("Search Shoe Items");
        btnSearchShoe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchShoeActionPerformed(evt);
            }
        });

        btnCreateCashier.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCreateCashier.setText("Create Cashier Account");
        btnCreateCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCashierActionPerformed(evt);
            }
        });

        btnApprovals.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnApprovals.setText("Approvals & Returns");
        btnApprovals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApprovalsActionPerformed(evt);
            }
        });

        btnPricing.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPricing.setText("Manage Pricing Rules");
        btnPricing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPricingActionPerformed(evt);
            }
        });

        btnAddShoe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddShoe.setText("Add New Shoe Item");
        btnAddShoe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddShoeActionPerformed(evt);
            }
        });

        btnUpdateProfile.setBackground(new java.awt.Color(255, 102, 204));
        btnUpdateProfile.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdateProfile.setText(" My Profile");
        btnUpdateProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProfileActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(0, 0, 51));
        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnApprovals1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnApprovals1.setText("Manage Suppliers");
        btnApprovals1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApprovals1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSearchShoe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddCategory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCheckStock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewShoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddShoe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnPricing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateCashier, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(btnApprovals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdateProfile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnApprovals1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(105, 105, 105))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateCashier, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddShoe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPricing, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchShoe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApprovals, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewShoes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApprovals1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheckStock, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewShoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewShoesActionPerformed
       ViewShoes viewPage = new ViewShoes("Manager"); // cleate ViewShoes class object
       viewPage.setVisible(true);
       this.dispose();  // close this dashboard
    }//GEN-LAST:event_btnViewShoesActionPerformed

    private void btnCheckStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckStockActionPerformed
       StockView stockPage = new StockView("Manager");  //create object of StockView class  
       stockPage.setVisible(true);
   
       this.dispose(); // cloase this dashboard
    }//GEN-LAST:event_btnCheckStockActionPerformed

    private void btnCreateCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCashierActionPerformed
        UserRegistration createPage = new UserRegistration();  // go to UserRegistration page
        createPage.setVisible(true);
        
        this.dispose();  // close this dashboard
    }//GEN-LAST:event_btnCreateCashierActionPerformed

    private void btnSearchShoeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchShoeActionPerformed
        SearchItems searchPage = new SearchItems("Manager"); //create SearchItems class object
        searchPage.setVisible(true);  // open search window
        this.dispose();  // close this dashboard
    }//GEN-LAST:event_btnSearchShoeActionPerformed

    private void btnApprovalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApprovalsActionPerformed
       // create object of ApprovalsReturns JFrame
    ApprovalsReturns approvalPage = new ApprovalsReturns("Manager");
    
    // Show ApprovalsReturns page
    approvalPage.setVisible(true);
    
    // close this dashboard
    this.dispose();
    }//GEN-LAST:event_btnApprovalsActionPerformed

    private void btnPricingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPricingActionPerformed
      PricingRules pr = new PricingRules();
      pr.setVisible(true);
      this.dispose();  // close this dashbaord
    }//GEN-LAST:event_btnPricingActionPerformed

    private void btnAddShoeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddShoeActionPerformed

    AddShoe addShoeWindow = new AddShoe("Manager"); // create AddShoe class object
    
    addShoeWindow.setVisible(true);  //show that window
    this.dispose();  // close this dashboard
    }//GEN-LAST:event_btnAddShoeActionPerformed

    private void btnUpdateProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProfileActionPerformed
     this.dispose(); // close this dashboard
    
    UpdateProfile profilePage = new UpdateProfile(); //create object of UpdateProfile page
   
    profilePage.setVisible(true); // open this page(UpdateProfile)
    }//GEN-LAST:event_btnUpdateProfileActionPerformed

    private void btnAddCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCategoryActionPerformed
      new CategoryManagement(this.userRole).setVisible(true);
      this.dispose();                                          

    }//GEN-LAST:event_btnAddCategoryActionPerformed

    private void btnApprovals1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApprovals1ActionPerformed
       // create SupplierManagement object 
    SupplierManagement supPage = new SupplierManagement();
    
    // show that page
    supPage.setVisible(true);
    
    // close this dashboard
    this.dispose();
    }//GEN-LAST:event_btnApprovals1ActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
      int a = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout", JOptionPane.YES_NO_OPTION); //Show a confirm message
    
     if (a == JOptionPane.YES_OPTION) {
        this.dispose(); // close this dashboard
        
        LoginFrame login = new LoginFrame();
        login.setVisible(true); // Show login page
    }
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCategory;
    private javax.swing.JButton btnAddShoe;
    private javax.swing.JButton btnApprovals;
    private javax.swing.JButton btnApprovals1;
    private javax.swing.JButton btnCheckStock;
    private javax.swing.JButton btnCreateCashier;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPricing;
    private javax.swing.JButton btnSearchShoe;
    private javax.swing.JButton btnUpdateProfile;
    private javax.swing.JButton btnViewShoes;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
